repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      args: [--line-length=79]
      exclude: ^.*\b(migrations)\b.*$
      language_version: python3.10
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: ^.*\b(migrations)\b.*$