version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres-database
    restart: always
    ports:
      - '5433:5432'
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    container_name: django-project
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
