# Generated by Django 4.0.1 on 2022-02-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="mode",
        ),
    ]
